name: planta_app
description: "Application de gestion d'arrosage des plantes"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.0.4
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  go_router: ^16.2.4
  get_it: ^8.2.0
  flutter_bloc: ^9.1.1

  firebase_core: ^3.7.0
  firebase_auth: ^5.4.0
  firebase_auth_web: ^5.8.15
  cloud_firestore: ^5.4.4

  dartz: ^0.10.1
  internet_connection_checker: ^3.0.1
  validators: ^3.0.0

dependency_overrides:
  js: ^0.6.7
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-light.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
